# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5846e01ea601ed087e5837792b0232b047a1ee672c198abb8b6f5ce078edac053ee0e2c504125c9bcbfd3e1c46cb195b4fc68a62bbe0a9b8b814613e0e9c797

test:
  secret_key_base: 941af87210e51f86ee368dbb7a856e520785f455b93f362c83d1cfdde847aedc13b32a34720141fcd6d43821cd281008f4bfca18d560fa4c7502a954f0fee835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
